Repository ASFHyP3/hyp3-autorift, pull requests merged in 2022-11, with the labels that each got.

#177 Release v0.9.0
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  hyp3_autorift/io.py
  hyp3_autorift/process.py
  hyp3_autorift/vend/CHANGES-L9.diff
  hyp3_autorift/vend/CHANGES-METADATA-2.diff
  hyp3_autorift/vend/CHANGES-METADATA-3.diff
  hyp3_autorift/vend/CHANGES-METADATA.diff
  hyp3_autorift/vend/CHANGES-S2-WEST.diff
  hyp3_autorift/vend/CHANGES.diff
  hyp3_autorift/vend/README.md
  hyp3_autorift/vend/netcdf_output.py
  hyp3_autorift/vend/testGeogridOptical.py
  hyp3_autorift/vend/testGeogrid_ISCE.py
  hyp3_autorift/vend/testautoRIFT.py
  hyp3_autorift/vend/testautoRIFT_ISCE.py
  tests/test_process.py
Labels: minor

#180 Fix dtype error in netcdf packaging for landsat
  hyp3_autorift/vend/CHANGES-176.diff
  hyp3_autorift/vend/README.md
  hyp3_autorift/vend/netcdf_output.py
Labels: bug, bumpless

#179 Release 0.9.1 -- metadata patches
  CHANGELOG.md
  hyp3_autorift/vend/CHANGES-176.diff
  hyp3_autorift/vend/README.md
  hyp3_autorift/vend/netcdf_output.py
  hyp3_autorift/vend/testautoRIFT.py
  hyp3_autorift/vend/testautoRIFT_ISCE.py
Labels: patch

#183 fix correction_level_img bug
  hyp3_autorift/vend/CHANGES-183.diff
  hyp3_autorift/vend/README.md
  hyp3_autorift/vend/testautoRIFT.py
  hyp3_autorift/vend/testautoRIFT_ISCE.py
Labels: bumpless

#184 better handling of antimeridian when determining parameter file based on scene geometry
  hyp3_autorift/geometry.py
  hyp3_autorift/io.py
  tests/test_geometry.py
  tests/test_io.py
Labels: bumpless

#192 Release v0.10.1
  CHANGELOG.md
  hyp3_autorift/vend/CHANGES-189.diff
  hyp3_autorift/vend/CHANGES-191.diff
  hyp3_autorift/vend/CHANGES-194.diff
  hyp3_autorift/vend/README.md
  hyp3_autorift/vend/netcdf_output.py
  hyp3_autorift/vend/testautoRIFT.py
  hyp3_autorift/vend/testautoRIFT_ISCE.py
  tests/test_netcdf_output.py
Labels: patch

#195 Add more info to vendored readme
  hyp3_autorift/vend/README.md
Labels: bumpless
