Repository ASFHyP3/hyp3-autorift, pull requests merged in 2022-02, with the labels that each got.

#137 Change checking env so it returns None
  hyp3_autorift/__main__.py
Labels: bumpless

#138 Pin opencv to fix linking issue
  CHANGELOG.md
  environment.yml
Labels: bug

#139 Release 0.7.5 -- EDL auth and opencv fix
  .github/queries/associated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  hyp3_autorift/__main__.py
Labels: patch

#141 Release Landsat 9 support
  CHANGELOG.md
  hyp3_autorift/vend/CHANGES-L9.diff
  hyp3_autorift/vend/README.md
  hyp3_autorift/vend/testGeogridOptical.py
  hyp3_autorift/vend/testGeogrid_ISCE.py
Labels: minor
