Repository ASFHyP3/hyp3-autorift, pull requests merged in 2022-10, with the labels that each got.

#163 Enable dependabot for action version updates
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
Labels: bumpless, CI/CD

#165 Fix dependabot
  .github/dependabot.yml
Labels: bumpless, CI/CD

#167 fft fix copy paste error
  hyp3_autorift/process.py
Labels: bumpless

#166 use different wallis filter for Sentinel-1
  CHANGELOG.md
  hyp3_autorift/vend/CHANGES-WALLIS-WIDTH.diff
  hyp3_autorift/vend/README.md
  hyp3_autorift/vend/testautoRIFT.py
  hyp3_autorift/vend/testautoRIFT_ISCE.py
Labels: bug

#168 Sync with upstream and fix platform
  environment.yml
  hyp3_autorift/io.py
  hyp3_autorift/process.py
  hyp3_autorift/vend/netcdf_output.py
  hyp3_autorift/vend/testGeogridOptical.py
  hyp3_autorift/vend/testGeogrid_ISCE.py
  hyp3_autorift/vend/testautoRIFT.py
  hyp3_autorift/vend/testautoRIFT_ISCE.py
Labels: bug, bumpless

#169 update autorift builds to encorporate wallis filter changes upstream
  environment.yml
Labels: bumpless

#171 Configure before setting filter width
  environment.yml
  hyp3_autorift/vend/testautoRIFT.py
  hyp3_autorift/vend/testautoRIFT_ISCE.py
Labels: bug, bumpless
