Repository ASFHyP3/hyp3-autorift, pull requests merged in 2023-09, with the labels that each got.

#228 fix typo
  hyp3_autorift/vend/CHANGES-189.diff
  hyp3_autorift/vend/netcdf_output.py
Labels: bumpless

#233 Proposed changes to #232
  CHANGELOG.md
  hyp3_autorift/crop.py
  hyp3_autorift/vend/CHANGES-232.diff
Labels: bumpless

#232 Speedup crop_netcdf_product
  hyp3_autorift/crop.py
Labels: patch, bumpless

#234 Release v0.12.0
  .github/workflows/create-jira-issue.yml
  CHANGELOG.md
  environment.yml
  hyp3_autorift/crop.py
  hyp3_autorift/process.py
  hyp3_autorift/vend/CHANGES-189.diff
  hyp3_autorift/vend/CHANGES-227.diff
  hyp3_autorift/vend/README.md
  hyp3_autorift/vend/netcdf_output.py
  setup.py
Labels: minor
