Repository ASFHyP3/hyp3-autorift, pull requests merged in 2024-07, with the labels that each got.

#281 Update m11/m12 calculation in S1 correction workflow
  src/hyp3_autorift/s1_isce2.py
Labels: bumpless

#278 Release 0.18.0
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  pyproject.toml
  src/hyp3_autorift/crop.py
  src/hyp3_autorift/process.py
  src/hyp3_autorift/s1_correction.py
  src/hyp3_autorift/s1_isce2.py
  src/hyp3_autorift/utils.py
Labels: minor

#284 Fix str when a Path is expected
  CHANGELOG.md
  src/hyp3_autorift/s1_isce2.py
Labels: bug

#285 Release v0.18.1 -- Correction fixes
  CHANGELOG.md
  src/hyp3_autorift/s1_isce2.py
Labels: patch
