Repository ASFHyP3/hyp3-autorift, pull requests merged in 2024-05, with the labels that each got.

#253 Update dependabot.yml to weekly
  .github/dependabot.yml
Labels: bumpless

#254 Don't crop when there is no data
  CHANGELOG.md
  src/hyp3_autorift/io.py
  src/hyp3_autorift/process.py
  src/hyp3_autorift/s1_correction.py
  src/hyp3_autorift/utils.py
  src/hyp3_autorift/vend/CHANGES.diff
  src/hyp3_autorift/vend/README.md
  src/hyp3_autorift/vend/testautoRIFT.py
  src/hyp3_autorift/vend/testautoRIFT_ISCE.py
  tests/test_entrypoints.py
  tests/test_io.py
  tests/test_process.py
  tests/test_utils.py
Labels: bug

#255 Release v0.16.0
  .github/dependabot.yml
  CHANGELOG.md
  src/hyp3_autorift/io.py
  src/hyp3_autorift/process.py
  src/hyp3_autorift/s1_correction.py
  src/hyp3_autorift/utils.py
  src/hyp3_autorift/vend/CHANGES.diff
  src/hyp3_autorift/vend/README.md
  src/hyp3_autorift/vend/testautoRIFT.py
  src/hyp3_autorift/vend/testautoRIFT_ISCE.py
  tests/test_entrypoints.py
  tests/test_io.py
  tests/test_process.py
  tests/test_utils.py
Labels: minor

#257 Update readme
  README.md
  docs/api_example.md
  docs/imgs/get_jobs_query.png
  docs/imgs/get_user_execute.png
  docs/imgs/get_user_try.png
  docs/imgs/post_jobs_execute.png
  docs/imgs/vertex-sign-in.png
  docs/sdk_example.ipynb
Labels: bumpless

#260 Isolate isce2 processing for Sentinel-1
  src/hyp3_autorift/geometry.py
  src/hyp3_autorift/process.py
  src/hyp3_autorift/s1_correction.py
  src/hyp3_autorift/s1_isce2.py
  src/hyp3_autorift/utils.py
  src/hyp3_autorift/vend/testautoRIFT_ISCE.py
Labels: bumpless

#267 Isolate isce2
  src/hyp3_autorift/geometry.py
  src/hyp3_autorift/process.py
  src/hyp3_autorift/s1_correction.py
  src/hyp3_autorift/s1_isce2.py
  src/hyp3_autorift/utils.py
  src/hyp3_autorift/vend/testautoRIFT_ISCE.py
Labels: bumpless
